# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6a61cc50d7865802da04656268180be044608c8488d5dbd07cd1236b7ec49c4706319688ac83c34de7c92520e9a247e941838d11007f4578c21f85303219a6

test:
  secret_key_base: 02a2e7bd69306be8aa313cc6cf1ab5f5f30730b0f95da699631b39c7b3b4306d000695cb617176d645f88a05ac069c3e0620db746f72546c7078421338653503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>