# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d3b99f1ed617316d62af39d8d3326700ae8979244f6ff22f199309d68daae27ab70ddd15f6ed71112866dd171f0349ff76ef09de18d95d2c164c7b472cc7e7

test:
  secret_key_base: e2e538b5669b9eab6435c44b88e6a3f41852ea1198faea35e2ae0befb89d86a6c3c5adea21834838e66927e1314a2ea3cc617c08091f60c5e114d48f1a6aded5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
